### ISSUE TITLE
Idea for more contributions

### ISSUE THREAD

**Issue by Anant016** [fsfe/reuse-website#11]
You can add a new page- To successfully merge 5 pull requests in https://github.com/fsfe, in 2 months, and get free stickers. This would help in more contributions, exposure, coz let's face it everybody likes free stuff :smiley: And this would be a great step, I think.

**Comment by mxmehl** [comment]
I am afraid this is useless, because the FSFE already offers this, even without a number of pull requests ;)

https://fsfe.org/contribute/spreadtheword

Obviously, the idea behind it is not to just throw around with stickers but use them to promote the idea of Free Software and certain campaigns, but it's free of charge. So I'd close this issue.

However, if we had REUSE stickers (which we should definitely work on!), mentioning those somewhere is a good idea, so thanks!
